name: shootout-goalie-debug
mode: train
input:
  scenarios:
    - name: ShootoutGoalie1
      save-state: Shootout-Goalie-1p-1.state
      scorekeeper: shootout-goalie
  metascorekeeper: nudged-median
  controller-discretizer: 2-button-bc
  feature-vector: players_and_puck
  load-checkpoint:
    latest: false
    specific-filename: null
  neat-config:
    NEAT:
      pop_size: 50
movie:
  enabled: generations
  stoppage-time-s: 3.0
render-live: False
nproc: 1