name: shootout-debug
mode: train
input:
  scenarios:
    - name: ShootoutShooter1
      save-state: Shootout-Shooter-1p-1.state
      scorekeeper: shootout-shooter
  metascorekeeper: nudged-median
  controller-discretizer: 2-button-bc
  feature-vector: players_and_puck
  load-checkpoint: false
  neat-config:
    NEAT:
      pop_size: 250
movie:
  enabled: generations
  stoppage-time-s: 3.0
render-live: False
nproc: null