name: default
mode: train
input:
  scenarios:
    - name: Score1
      save-state: ChiAtBuf-Faceoff.state
      scorekeeper: game-scoring-1
    - name: Score2
      save-state: ChiAtBuf-Faceoff-2.state
      scorekeeper: game-scoring-1
    - name: Score3
      save-state: ChiAtBuf-Faceoff-3.state
      scorekeeper: game-scoring-1
    - name: Score4
      save-state: ChiAtBuf-Faceoff-4.state
      scorekeeper: game-scoring-1
  metascorekeeper: mean
  controller-discretizer: 2-button-bc
  feature-vector: players_and_puck
  neat-config:
    NEAT:
      pop_size: 250
movie:
  enabled: generations
  stoppage-time-s: 5.0
render-live: False
nproc: null