name: default
mode: train
input:
  scenarios:
    - name: basic
      save-state: BufAtChi-Faceoff.state
      scorekeeper: game-scoring-1
  metascorekeeper: summer
  controller-discretizer: 3-button
  feature-vector: players_and_puck
  neat-config:
    NEAT:
      pop_size: 30
movie:
  enabled: generations
  stoppage-time-s: 5.0
render-live: False
nproc: null