mode: train
input:
  scenarios:
    - scenario: BufAtChi-Faceoff.state
      scorekeeper: winning-faceoff-1
  metascorekeeper: Trivial
movie:
  enabled: generations
  stoppage-time-s: 5.0
render-live: False
nproc: null