name: default
mode: train
input:
  scenarios:
    - name: basic
      save-state: BufAtChi-Faceoff.state
      scorekeeper: point-per-frame
  metascorekeeper: summer
  feature-vector: players_and_puck
movie:
  enabled: generations
  stoppage-time-s: 5.0
render-live: False
nproc: null